language: python
sudo: false
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=elcflow --cov-config ./tests/.coveragerc
after_success:
  - coveralls
deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  on:
    tags: true
    branch: master